### ISSUE TITLE
Create a landing page that I can host on notionvault.com

### ISSUE THREAD

**Issue by Theo-Farnole** [Theo-Farnole/notion-app-backup#17]
Lambda users don't know how to use Github. 

We need a simple page to share the software and download it easily. 

And in addition, we will be referenced in search engines

**Comment by Theo-Farnole** [comment]
References
1. https://www.campsite.design/?ref=lapaninja
2. https://astro.build/?ref=lapaninja
3. https://skiff.com/?ref=lapaninja
4. https://ready.so/?ref=lapaninja#Get-Ready

List of ideas https://www.lapa.ninja/category/software/

**Comment by Theo-Farnole** [comment]
**TODO**

- [X] improve the screenshot
- [X] add color to the homepage
- [X] add title + description
- [X] host somewhere
- [X] analyze SEO
